### ISSUE TITLE
feature request - `/posts/explore` and `/posts/feed` with range

### ISSUE THREAD

**Issue by idaned** [dantc12/grulo_backend#23]

**Comment by dantc12** [comment]
Explain

**Comment by idaned** [comment]
@dantc12 
The concept of "explore posts" is showing posts from the "explore groups", filtered by time.
That means, I expect to see as the current example, by order:

1. First post from the last hour in the group hamatmid 22
2. Second post from two hours ago from the group ramat fan
3. Third post from yesterday from the group Hamatmid Street

Currently, I need to call multiple times to GET /posts for each "explore group" and filter it myself by timestamp, which will cost frontend processing which is oh no very bad. 

So, I will need the ability to call /posts/?group_name=AA,BB,CC

Alternatively, make an API for /posts/explore/
(I thought we didn't need it but apparently we do)

**Comment by dantc12** [comment]
Should be working in branch `feature/range_search`
